"use client";

// Resolves the AI icon-mapper's controlled vocabulary (lib/pipeline/schema.js
// ICON_TAXONOMY) to real lucide-react components. The AI only ever returns a
// tag string from that fixed list — it never draws or invents an icon — so
// this map is the single place actual icon assets get chosen.

import {
  BookOpen,
  Lightbulb,
  Target,
  CheckCircle2,
  Search,
  Settings,
  BarChart3,
  ArrowRight,
  Flag,
  Star,
  Shield,
  Rocket,
  Clock,
  Database,
  Cpu,
  Globe,
  User,
  Users,
  Zap,
  Lock,
  Code,
  Terminal,
  DollarSign,
  TrendingUp,
  Layers,
  FileText,
  Award,
  Heart,
  Briefcase,
  Compass,
  Grid3x3,
  Box,
  Key,
  AlertTriangle,
  CheckCircle,
  Info,
  HelpCircle,
  Circle,
} from "lucide-react";

export const ICON_MAP = {
  book: BookOpen,
  lightbulb: Lightbulb,
  target: Target,
  checkmark: CheckCircle2,
  "magnifying-glass": Search,
  gear: Settings,
  "bar-chart": BarChart3,
  arrow: ArrowRight,
  flag: Flag,
  star: Star,
  shield: Shield,
  rocket: Rocket,
  clock: Clock,
  database: Database,
  cpu: Cpu,
  globe: Globe,
  user: User,
  users: Users,
  zap: Zap,
  lock: Lock,
  code: Code,
  terminal: Terminal,
  dollar: DollarSign,
  "trending-up": TrendingUp,
  layers: Layers,
  "file-text": FileText,
  award: Award,
  heart: Heart,
  briefcase: Briefcase,
  compass: Compass,
  grid: Grid3x3,
  box: Box,
  key: Key,
  "alert-triangle": AlertTriangle,
  "check-circle": CheckCircle,
  info: Info,
  "help-circle": HelpCircle,
  "generic-dot": Circle,
};

export function getIconComponent(tag) {
  return ICON_MAP[tag] || Circle;
}
